### 处理数据集

In [77]:
import numpy as np
import pandas as pd

In [78]:
train = pd.read_csv("train_users_2.csv")
test = pd.read_csv("test_users.csv")
# 标签列
labels = train['country_destination'].values

In [79]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 213451 entries, 0 to 213450
Data columns (total 16 columns):
id                         213451 non-null object
date_account_created       213451 non-null object
timestamp_first_active     213451 non-null int64
date_first_booking         88908 non-null object
gender                     213451 non-null object
age                        125461 non-null float64
signup_method              213451 non-null object
signup_flow                213451 non-null int64
language                   213451 non-null object
affiliate_channel          213451 non-null object
affiliate_provider         213451 non-null object
first_affiliate_tracked    207386 non-null object
signup_app                 213451 non-null object
first_device_type          213451 non-null object
first_browser              213451 non-null object
country_destination        213451 non-null object
dtypes: float64(1), int64(2), object(13)
memory usage: 26.1+ MB

### 处理首次活跃特征

In [80]:
# 删除训练集的 date_first_booking,country_destination列

# 删除测试集的 date_first_booking

# 整合训练集和测试集

data.head()

,id,date_account_created,timestamp_first_active,gender,age,signup_method,signup_flow,language,affiliate_channel,affiliate_provider,first_affiliate_tracked,signup_app,first_device_type,first_browser
0,gxn3p5htnn,2010-06-28,20090319043255,-unknown-,NaN,facebook,0,en,direct,direct,untracked,Web,Mac Desktop,Chrome
1,820tgsjxq7,2011-05-25,20090523174809,MALE,38.0,facebook,0,en,seo,google,untracked,Web,Mac Desktop,Chrome
2,4ft3gnwmtx,2010-09-28,20090609231247,FEMALE,56.0,basic,3,en,direct,direct,untracked,Web,Windows Desktop,IE
3,bjjt8pjhuk,2011-12-05,20091031060129,FEMALE,42.0,facebook,0,en,direct,direct,untracked,Web,Mac Desktop,Firefox
4,87mebub9p4,2010-09-14,20091208061105,-unknown-,41.0,basic,0,en,direct,direct,untracked,Web,Mac Desktop,Chrome

In [81]:
# 构造首次激活列
from datetime import datetime
data['first_active'] = 
data.head()

,id,date_account_created,timestamp_first_active,gender,age,signup_method,signup_flow,language,affiliate_channel,affiliate_provider,first_affiliate_tracked,signup_app,first_device_type,first_browser,first_active
0,gxn3p5htnn,2010-06-28,20090319043255,-unknown-,NaN,facebook,0,en,direct,direct,untracked,Web,Mac Desktop,Chrome,2009-03-19 04:32:55
1,820tgsjxq7,2011-05-25,20090523174809,MALE,38.0,facebook,0,en,seo,google,untracked,Web,Mac Desktop,Chrome,2009-05-23 17:48:09
2,4ft3gnwmtx,2010-09-28,20090609231247,FEMALE,56.0,basic,3,en,direct,direct,untracked,Web,Windows Desktop,IE,2009-06-09 23:12:47
3,bjjt8pjhuk,2011-12-05,20091031060129,FEMALE,42.0,facebook,0,en,direct,direct,untracked,Web,Mac Desktop,Firefox,2009-10-31 06:01:29
4,87mebub9p4,2010-09-14,20091208061105,-unknown-,41.0,basic,0,en,direct,direct,untracked,Web,Mac Desktop,Chrome,2009-12-08 06:11:05

In [82]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 275547 entries, 0 to 275546
Data columns (total 15 columns):
id                         275547 non-null object
date_account_created       275547 non-null object
timestamp_first_active     275547 non-null int64
gender                     275547 non-null object
age                        158681 non-null float64
signup_method              275547 non-null object
signup_flow                275547 non-null int64
language                   275547 non-null object
affiliate_channel          275547 non-null object
affiliate_provider         275547 non-null object
first_affiliate_tracked    269462 non-null object
signup_app                 275547 non-null object
first_device_type          275547 non-null object
first_browser              275547 non-null object
first_active               275547 non-null datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(2), object(11)
memory usage: 31.5+ MB

In [83]:
# 构造激活日期的年,月,日特征
data['year'] = 
data['month'] = 
data['day'] = 
# 构造工作日特征
data['weekday'] = data.first_active.apply(lambda x:x.isoweekday())
data.head()

,id,date_account_created,timestamp_first_active,gender,age,signup_method,signup_flow,language,affiliate_channel,affiliate_provider,first_affiliate_tracked,signup_app,first_device_type,first_browser,first_active,year,month,day,weekday
0,gxn3p5htnn,2010-06-28,20090319043255,-unknown-,NaN,facebook,0,en,direct,direct,untracked,Web,Mac Desktop,Chrome,2009-03-19 04:32:55,2009,3,19,4
1,820tgsjxq7,2011-05-25,20090523174809,MALE,38.0,facebook,0,en,seo,google,untracked,Web,Mac Desktop,Chrome,2009-05-23 17:48:09,2009,5,23,6
2,4ft3gnwmtx,2010-09-28,20090609231247,FEMALE,56.0,basic,3,en,direct,direct,untracked,Web,Windows Desktop,IE,2009-06-09 23:12:47,2009,6,9,2
3,bjjt8pjhuk,2011-12-05,20091031060129,FEMALE,42.0,facebook,0,en,direct,direct,untracked,Web,Mac Desktop,Firefox,2009-10-31 06:01:29,2009,10,31,6
4,87mebub9p4,2010-09-14,20091208061105,-unknown-,41.0,basic,0,en,direct,direct,untracked,Web,Mac Desktop,Chrome,2009-12-08 06:11:05,2009,12,8,2

In [84]:
data.weekday.value_counts()

2    45514
3    43847
1    41926
4    41883
5    38076
6    32212
7    32089
Name: weekday, dtype: int64

In [85]:
# 删除timestamp_first_active列

data.head()

,id,date_account_created,gender,age,signup_method,signup_flow,language,affiliate_channel,affiliate_provider,first_affiliate_tracked,signup_app,first_device_type,first_browser,first_active,year,month,day,weekday
0,gxn3p5htnn,2010-06-28,-unknown-,NaN,facebook,0,en,direct,direct,untracked,Web,Mac Desktop,Chrome,2009-03-19 04:32:55,2009,3,19,4
1,820tgsjxq7,2011-05-25,MALE,38.0,facebook,0,en,seo,google,untracked,Web,Mac Desktop,Chrome,2009-05-23 17:48:09,2009,5,23,6
2,4ft3gnwmtx,2010-09-28,FEMALE,56.0,basic,3,en,direct,direct,untracked,Web,Windows Desktop,IE,2009-06-09 23:12:47,2009,6,9,2
3,bjjt8pjhuk,2011-12-05,FEMALE,42.0,facebook,0,en,direct,direct,untracked,Web,Mac Desktop,Firefox,2009-10-31 06:01:29,2009,10,31,6
4,87mebub9p4,2010-09-14,-unknown-,41.0,basic,0,en,direct,direct,untracked,Web,Mac Desktop,Chrome,2009-12-08 06:11:05,2009,12,8,2

In [86]:
# 定义一个季节生成函数
def gen_season(param):
    
# 此函数只适应于北半球温带及寒带，不适合赤道地区和南半球，需要谨慎对待

In [87]:
# 根据月份生成季节列
data['season'] = 
data.season.value_counts()

summer    99197
spring    68108
autumn    60771
winter    47471
Name: season, dtype: int64

### 独热编码(onehot encoder)

假设某列(或称之为特征)有4种取值方式 初中,高中,本科,硕士

独热编码之后某一行的学历特征就变成了了4列,比如初中变成了0001,高中变成了0010,本科变成了0100,硕士变成了1000

In [88]:
# 把首次活跃日期的季节独热编码
df_season = pd.get_dummies(data.season, prefix='season')
data = pd.concat((data,df_season),axis=1)
# 把首次活跃日期的星期独热编码

# 删除季节和星期列

data.head()

,id,date_account_created,gender,age,signup_method,signup_flow,language,affiliate_channel,affiliate_provider,first_affiliate_tracked,...,season_spring,season_summer,season_winter,actwd_1,actwd_2,actwd_3,actwd_4,actwd_5,actwd_6,actwd_7
0,gxn3p5htnn,2010-06-28,-unknown-,NaN,facebook,0,en,direct,direct,untracked,...,1,0,0,0,0,0,1,0,0,0
1,820tgsjxq7,2011-05-25,MALE,38.0,facebook,0,en,seo,google,untracked,...,1,0,0,0,0,0,0,0,1,0
2,4ft3gnwmtx,2010-09-28,FEMALE,56.0,basic,3,en,direct,direct,untracked,...,0,1,0,0,1,0,0,0,0,0
3,bjjt8pjhuk,2011-12-05,FEMALE,42.0,facebook,0,en,direct,direct,untracked,...,0,0,0,0,0,0,0,0,1,0
4,87mebub9p4,2010-09-14,-unknown-,41.0,basic,0,en,direct,direct,untracked,...,0,0,1,0,1,0,0,0,0,0

### 处理账户创建时间特征

In [89]:
# 把账户创建日期转化成日期格式
dac = 
# 获取month列
dac_month = 
# 依据month生成season列
dac_season = 
dac_season.head()

0    summer
1    spring
2    autumn
3    winter
4    autumn
Name: date_account_created, dtype: object

In [90]:
# 季节列哑编码
df_dac = 
# 连接数据
data = 
data.head()

,id,date_account_created,gender,age,signup_method,signup_flow,language,affiliate_channel,affiliate_provider,first_affiliate_tracked,...,actwd_2,actwd_3,actwd_4,actwd_5,actwd_6,actwd_7,dac_autumn,dac_spring,dac_summer,dac_winter
0,gxn3p5htnn,2010-06-28,-unknown-,NaN,facebook,0,en,direct,direct,untracked,...,0,0,1,0,0,0,0,0,1,0
1,820tgsjxq7,2011-05-25,MALE,38.0,facebook,0,en,seo,google,untracked,...,0,0,0,0,1,0,0,1,0,0
2,4ft3gnwmtx,2010-09-28,FEMALE,56.0,basic,3,en,direct,direct,untracked,...,1,0,0,0,0,0,1,0,0,0
3,bjjt8pjhuk,2011-12-05,FEMALE,42.0,facebook,0,en,direct,direct,untracked,...,0,0,0,0,1,0,0,0,0,1
4,87mebub9p4,2010-09-14,-unknown-,41.0,basic,0,en,direct,direct,untracked,...,1,0,0,0,0,0,1,0,0,0

In [92]:
# 构造注册日期和首次活跃日期的时间差
time_diff = 
time_diff.value_counts()

 0       275369
-1            7
-6            4
-7            4
-2            4
-3            3
-4            3
-5            3
-29           3
-634          2
-104          2
-40           2
-37           2
-95           2
-176          2
-722          2
-20           2
-103          2
-312          2
-57           2
-9            2
-163          2
-153          1
-658          1
-665          1
-154          1
-150          1
-659          1
-167          1
-169          1
          ...
-328          1
-74           1
-369          1
-111          1
-367          1
-622          1
-108          1
-364          1
-514          1
-616          1
-359          1
-358          1
-101          1
-356          1
-354          1
-349          1
-92           1
-91           1
-1369         1
-86           1
-595          1
-851          1
-337          1
-1361         1
-80           1
-78           1
-76           1
-331          1
-587          1
-362          1
Length: 143, dtype: int64

In [93]:
"""
创建一个间隔函数,对首次激活和创建账户之间的间隔进行分类,
间隔0返回一天之内,间隔1天到30天返回一月之内,间隔30天到365天返回一年之内,其余的返回其他
"""
def gen_span(param):

In [94]:
# 生成间隔列
data['span'] = 
data.head()

,id,date_account_created,gender,age,signup_method,signup_flow,language,affiliate_channel,affiliate_provider,first_affiliate_tracked,...,actwd_3,actwd_4,actwd_5,actwd_6,actwd_7,dac_autumn,dac_spring,dac_summer,dac_winter,span
0,gxn3p5htnn,2010-06-28,-unknown-,NaN,facebook,0,en,direct,direct,untracked,...,0,1,0,0,0,0,0,1,0,其他
1,820tgsjxq7,2011-05-25,MALE,38.0,facebook,0,en,seo,google,untracked,...,0,0,0,1,0,0,1,0,0,其他
2,4ft3gnwmtx,2010-09-28,FEMALE,56.0,basic,3,en,direct,direct,untracked,...,0,0,0,0,0,1,0,0,0,其他
3,bjjt8pjhuk,2011-12-05,FEMALE,42.0,facebook,0,en,direct,direct,untracked,...,0,0,0,1,0,0,0,0,1,其他
4,87mebub9p4,2010-09-14,-unknown-,41.0,basic,0,en,direct,direct,untracked,...,0,0,0,0,0,1,0,0,0,一年之内

In [95]:
# 对间隔特征进行独热编码
df_span = 
# 把独热特征与原数据缝合
data = 
# 删除间隔列

In [96]:
data.columns

Index(['id', 'date_account_created', 'gender', 'age', 'signup_method',
       'signup_flow', 'language', 'affiliate_channel', 'affiliate_provider',
       'first_affiliate_tracked', 'signup_app', 'first_device_type',
       'first_browser', 'first_active', 'year', 'month', 'day',
       'season_autumn', 'season_spring', 'season_summer', 'season_winter',
       'actwd_1', 'actwd_2', 'actwd_3', 'actwd_4', 'actwd_5', 'actwd_6',
       'actwd_7', 'dac_autumn', 'dac_spring', 'dac_summer', 'dac_winter',
       'span_一天之内', 'span_一年之内', 'span_一月之内', 'span_其他'],
      dtype='object')

In [97]:
# 丢弃账户创建日期和首次激活日期

In [98]:
data.isnull().sum()

id                              0
gender                          0
age                        116866
signup_method                   0
signup_flow                     0
language                        0
affiliate_channel               0
affiliate_provider              0
first_affiliate_tracked      6085
signup_app                      0
first_device_type               0
first_browser                   0
year                            0
month                           0
day                             0
season_autumn                   0
season_spring                   0
season_summer                   0
season_winter                   0
actwd_1                         0
actwd_2                         0
actwd_3                         0
actwd_4                         0
actwd_5                         0
actwd_6                         0
actwd_7                         0
dac_autumn                      0
dac_spring                      0
dac_summer                      0
dac_winter                      0
span_一天之内                       0
span_一年之内                       0
span_一月之内                       0
span_其他                         0
dtype: int64

### 处理年龄特征

In [99]:
# 处理年龄特征
data.age.value_counts()

30.0      7712
28.0      7687
29.0      7647
31.0      7540
27.0      7462
32.0      7187
33.0      6795
26.0      6745
34.0      6176
25.0      6149
35.0      5949
36.0      5032
24.0      4571
37.0      4474
38.0      4091
39.0      3642
23.0      3516
40.0      3327
41.0      3098
42.0      2731
45.0      2669
44.0      2584
22.0      2508
43.0      2486
46.0      2317
19.0      2023
47.0      2006
48.0      1779
50.0      1679
51.0      1630
          ...
1949.0       3
1936.0       2
1920.0       2
111.0        2
1938.0       2
1929.0       2
1923.0       2
1926.0       2
1944.0       2
1951.0       2
1940.0       2
1942.0       1
2002.0       1
150.0        1
1952.0       1
1945.0       1
2008.0       1
1939.0       1
2000.0       1
1995.0       1
1948.0       1
1968.0       1
1930.0       1
1941.0       1
1922.0       1
1954.0       1
1953.0       1
132.0        1
1937.0       1
112.0        1
Name: age, Length: 145, dtype: int64

- 可以看到有些人把年龄填成了出生日期,所以需要把这些数据清理

In [100]:
# 把年龄的空值填充成-1

In [101]:
# 定义函数把大于1900的数值处理为正常年龄
def calc_age(param):

In [102]:
# 处理年龄列数据
data.age = 
data.age.value_counts()

-1.0      116866
 30.0       7712
 28.0       7687
 29.0       7647
 31.0       7540
 27.0       7462
 32.0       7187
 33.0       6795
 26.0       6745
 34.0       6176
 25.0       6149
 35.0       5949
 36.0       5032
 24.0       4571
 37.0       4474
 38.0       4091
 39.0       3642
 23.0       3516
 40.0       3327
 41.0       3098
 42.0       2731
 45.0       2669
 44.0       2584
 22.0       2508
 43.0       2486
 46.0       2318
 19.0       2024
 47.0       2006
 48.0       1779
 50.0       1679
           ...
 82.0         31
 103.0        30
 107.0        28
 96.0         27
 84.0         25
 90.0         24
 93.0         21
 106.0        20
 92.0         19
 94.0         19
 89.0         19
 99.0         19
 88.0         17
 98.0         17
 108.0        16
 91.0         16
 115.0        13
 97.0         13
 15.0          9
 2.0           7
 13.0          5
 113.0         4
 4.0           3
 111.0         2
 150.0         1
 14.0          1
 12.0          1
 132.0         1
 6.0           1
 112.0         1
Name: age, Length: 112, dtype: int64

In [103]:
# 把年龄列离散化
div = 15
def get_age(age):
    # 将连续型转换为离散型
    if age < 0:
        return 'NaN' #空值
    elif (age < div):
        return div #如果年龄小于15岁，那么返回15岁
    elif (age <= div * 2):
        return div*2 #如果年龄大于15小于等于30岁，则返回30岁
    elif (age <= div * 3):
        return div * 3
    elif (age <= div * 4):
        return div * 4
    elif (age <= div * 5):
        return div * 5
    elif (age <= 110):
        return div * 6
    else:
        return 'Unphysical' #非正常年龄
data['age'] = data['age'].apply(get_age)
data.age.value_counts()

NaN           116866
45             67781
30             59465
60             21386
75              6483
90              2728
15               816
Unphysical        22
Name: age, dtype: int64

In [104]:
# 年龄独热编码
df_age = 
# 独热编码和原数据缝合
data = 
# 删除age

data.columns

Index(['id', 'gender', 'age', 'signup_method', 'signup_flow', 'language',
       'affiliate_channel', 'affiliate_provider', 'first_affiliate_tracked',
       'signup_app', 'first_device_type', 'first_browser', 'year', 'month',
       'day', 'season_autumn', 'season_spring', 'season_summer',
       'season_winter', 'actwd_1', 'actwd_2', 'actwd_3', 'actwd_4', 'actwd_5',
       'actwd_6', 'actwd_7', 'dac_autumn', 'dac_spring', 'dac_summer',
       'dac_winter', 'span_一天之内', 'span_一年之内', 'span_一月之内', 'span_其他',
       'age_15', 'age_30', 'age_45', 'age_60', 'age_75', 'age_90', 'age_NaN',
       'age_Unphysical'],
      dtype='object')

In [105]:
"""
把注册前第一个接触的市场渠道按年龄分组充填空值,
年轻人喜欢用脸书,年老的喜欢用推特,再老一些的喜欢看报纸
把各个年龄段的渠道空值用此年龄段的渠道众数填充
"""
data['first_affiliate_tracked'] =

In [106]:
data['first_affiliate_tracked'].value_counts()

untracked        143181
linked            62064
omg               54859
tracked-other      6655
product            2353
marketing           281
local ops            69
Name: first_affiliate_tracked, dtype: int64